project:
  type: book

book:
  title: "Advanced Financial Data Analytics"
  subtitle: "Time series econometrics, Bayesian methods, and machine learning"
  author: "Barry Quinn"
  cover-image: "images/DALL·E 2024-01-16 16.45.31 - A symbolic representation of embracing complexity in financial markets. The image shows a person in the center, surrounded by a whirl of abstract symb.png"
  date: '`r Sys.Date()`'
  chapters:
    - index.qmd
    - part: "Core Concepts"
      chapters:
        - primer.qmd
        - time_series.qmd
        - bayesian_methods.qmd
        - ml.qmd
    - part: "Advanced Material"
      chapters: 
        - multilevel.qmd
        - causal.qmd
        - colliderbias.qmd
    - references.qmd
  appendices: 
    - tools.qmd
    - resources.qmd
    - solutions.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



