project:
  type: book

book:
  title: "Don't Fence Me In"
  subtitle: "Advancing the Art and Science of Financial Analytics with Econometrics, Bayesian Methods, and Machine Learning"
  author: "Barry Quinn"
  cover-image: "images/stable_diffusion_cover.png"
  date: '`r Sys.Date()`'
  chapters:
    - index.qmd
    - part: "Core Concepts"
      chapters:
        - primer.qmd
        - tools.qmd
        - returns.qmd
        - time_series.qmd
        - bayesian_methods.qmd
        - ml.qmd
    - part: "Advanced Material"
      chapters: 
        - multilevel.qmd
        - causal.qmd
        - colliderbias.qmd
    - references.qmd
  appendices: 
    - resources.qmd
    - solutions.qmd
    - academic-integrity.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



