project:
  type: book

book:
  title: "Advanced Financial Data Analytics"
  subtitle: "A Modern Approach to Financial Research and Analytics"
  author: "Barry Quinn"
  cover-image: "images/logos/cover-image.png"
  date: '`r Sys.Date()`'
  chapters:
    - index.qmd
    - part: "Core Concepts"
      chapters:
        - primer.qmd
        - tools.qmd
        - returns.qmd
        - time_series.qmd
        - bayesian_methods.qmd
        - ml.qmd
    - part: "Advanced Material"
      chapters: 
        - multilevel.qmd
        - causal.qmd
        - colliderbias.qmd
    - references.qmd
  appendices: 
    - resources.qmd
    - solutions.qmd
    - academic-integrity.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



